In [2]:
import numpy as np

In [9]:
angka = np.array([2,3,4,5])
print(type(angka))

<class 'numpy.ndarray'>


In [4]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## Identity Matrix 

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Bilangan Distribusi Uniform(0-1) 

In [17]:
np.random.rand(5)

array([0.01831336, 0.68592443, 0.01564108, 0.57083404, 0.8304179 ])

In [19]:
np.random.rand(2,3)

array([[0.29726652, 0.18668594, 0.1343017 ],
       [0.72572019, 0.70403191, 0.22797194]])

## Bilangan Distribusi Normal

In [20]:
np.random.randn(3)

array([-1.35361156,  0.09935031, -1.29250667])

In [21]:
np.random.randn(3,5)

array([[ 2.01330788e+00,  8.17810356e-01,  2.42242210e+00,
         5.18171910e-01, -1.50059137e+00],
       [ 1.73413470e+00,  5.16772372e-01, -5.46064306e-01,
         1.92969473e-01,  2.29050546e-03],
       [ 2.41012135e-01,  3.57448268e-01,  4.06953764e-01,
         1.37808814e+00, -9.22952848e-01]])

In [8]:
np.random.randint(0,10)

5

In [21]:
bilangan = np.random.randint(2,50,100)

In [22]:
bilangan.reshape(10,10)

array([[34, 23, 42, 27, 41, 11, 28, 49, 48,  3],
       [19, 39, 19, 18, 20, 25, 36, 21, 42, 43],
       [38, 14, 32, 32, 17, 31, 16, 25, 47, 29],
       [ 3, 13,  2, 15, 33, 31, 10,  6, 37, 14],
       [36, 37, 31, 36, 47, 37, 28, 33,  3,  2],
       [20, 31, 13, 41, 48, 22, 49, 11, 42, 14],
       [37, 34, 11, 13, 45,  4,  9, 49, 39,  4],
       [14,  8, 32, 40, 30, 14, 27,  9,  6, 45],
       [14, 44, 14,  7, 23, 25, 11, 17, 46, 19],
       [12, 45, 35, 19, 14, 10, 46, 43, 12, 38]])